// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "angadsharma1016/omega/src/participants/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

//  NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreatePHandler(m, endpoints, options["CreateP"])
	makeReadPHandler(m, endpoints, options["ReadP"])
	makeUpdatePHandler(m, endpoints, options["UpdateP"])
	makeDeletePHandler(m, endpoints, options["DeleteP"])
	makeCreateFeedbackHandler(m, endpoints, options["CreateFeedback"])
	makeReadFeedbackHandler(m, endpoints, options["ReadFeedback"])
	makePostAttendanceHandler(m, endpoints, options["PostAttendance"])
	makeReadAttendanceHandler(m, endpoints, options["ReadAttendance"])
	return m
}
